twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]
    globals:
        attachments_directory: 'uploads/attachments/'
when@test:
    twig:
        strict_variables: true
